### PR TITLE
Temporary fix for #189

### LINKED ISSUE #189: IndexOutOfBounds Exception in VlangEnterHandlerDelegate.postProcessEnter
Where: [Line 27](https://github.com/i582/vlang-idea/blob/75a79195dfa2f65485820806498db50a933e7f81/src/main/kotlin/org/vlang/lang/completion/VlangEnterHandlerDelegate.kt#L27)

Stack trace: [Pastebin](https://pastebin.com/0NCq2ub9)

### PR DESCRIPTION
**Pull request by IkeVoodoo**
Fixes #189

There could be a better implementation for this, noted by the "TODO" comment

### CODE REVIEW

**Comment by i582** [comment]
why there is check for the ability to write to a file?

**Comment by IkeVoodoo** [comment]
It seemed fitting as it is editing the current file, I haven't worked much on extensions so it might not be required, if it is not, I'll remove it.

**Comment by i582** [comment]
I think you can remove this check, leave only one if with offset, also I think this is a sufficient solution, so you can remove the comments. And add a space after the `if` keyword.

**Comment by i582** [comment]
Thank you! Merged

**Pull request merged**
