### PR TITLE
Postfix Completion implementation

### LINKED ISSUE #150: Add support for postfix completion
See https://plugins.jetbrains.com/docs/intellij/postfix-completion.html

### PR DESCRIPTION
**Pull request by MohammadMD1383**
Fixes #150

### CODE REVIEW

**Comment by i582** [comment]
Looks cool and very useful!

Снимок экрана 2022-10-19 в 20 21 54

**Comment by i582** [comment]
Hi
Please tell me what else you want to do here? We could merge it and create other PRs for improvements. It would be cool to have this in the master at the start of the alpha test.

**Comment by MohammadMD1383** [comment]
Hi, I wanted to make it better but I'm really busy now.

If it is good enough to be merged, so do it.

I will mark this as ready for review

**Comment by i582** [comment]
Thank you! It's great contribution!

**Pull request merged**
