### PR TITLE
Improved toolchain settings 

### LINKED ISSUE #109: Try find toolchains in common places for settings

### LINKED ISSUE #219: Add validation of paths for stdlib, vmodules and v toolchain in settings
Perhaps it makes sense to show an error in the editor (with the ability to hide it) if one of the paths refers to an unknown folder / file.

### PR DESCRIPTION
**Pull request by i582**
## Example

Снимок экрана 2022-10-21 в 04 07 24

## Validation

Снимок экрана 2022-10-21 в 04 07 38

## In file

Снимок экрана 2022-10-21 в 04 12 09

Fixes #109 
Fixes #219

### CODE REVIEW

**Comment by i582** [comment]
@IkeVoodoo can you check that on Windows, when creating a project, you can select the path to V from the list?

**Comment by IkeVoodoo** [comment]
> @IkeVoodoo can you check that on Windows, when creating a project, you can select the path to V from the list?

I will, finishing to write up a PR description first

**Comment by IkeVoodoo** [comment]
image
It seems as if it is not detecting my v installation,

**Comment by i582** [comment]
I think I know what the problem is, I'll fix it now.

**Comment by i582** [comment]
Please, try again with last commit

**Pull request merged**
