### PR TITLE
Implements #5 and #178, Fixes #220 and #189 + a non-reported error and warning

### LINKED ISSUE #189: IndexOutOfBounds Exception in VlangEnterHandlerDelegate.postProcessEnter
Where: [Line 27](https://github.com/i582/vlang-idea/blob/75a79195dfa2f65485820806498db50a933e7f81/src/main/kotlin/org/vlang/lang/completion/VlangEnterHandlerDelegate.kt#L27)

Stack trace: [Pastebin](https://pastebin.com/0NCq2ub9)

### LINKED ISSUE #220: IndexOutOfBoundsException
Where: [Line 486](https://github.com/i582/vlang-idea/blob/84d6a458c33eb9581f8f53f6f261f4418343e626/src/main/kotlin/org/vlang/lang/completion/VlangCompletionUtil.kt#L486)
Stack trace: [Pastebin](https://pastebin.com/XLsPpq3V)

I can try to fix this myself

### PR DESCRIPTION
**Pull request by IkeVoodoo**
Partially Implements #5 (`main` check is missing)
Fully Implements #178 (Quick fix not implemented yet, lack of knowledge.)
 

Fixes #220 
Fixes #189

Fixes not reported IndexOutOfBoundsException
Fixes a warning in `VlangBuildTagsUI.kt` line 24 where the title was not capitalized properly
Fixes functions wit no return type that end with `!` or `?`, Like `fn (test int) !` auto-completing as  `fn (test int) !null`

Moved snake case checking to a separate method to reuse in module name checking (used to enforce module name convention in the [Modules](https://github.com/vlang/v/blob/master/doc/docs.md#modules) section)

### CODE REVIEW

**Comment by IkeVoodoo** [comment]
@i582 Could you please review this, and if possible, merge it?

**Comment by i582** [comment]
I'll take a look today.

**Comment by i582** [comment]
Sorry I took a break from the plugin, will be back next week :(

**Comment by IkeVoodoo** [comment]
Moved to #235

**Pull request closed without merging**
